# Generated by Django 4.0 on 2023-01-08 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0002_alter_tweet_good_count_alter_tweet_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pushed', models.BooleanField(default=False)),
                ('parend_id', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_users', to='tweet.user')),
            ],
        ),
        migrations.CreateModel(
            name='GoodParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parend_id', models.CharField(max_length=50)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='good.good')),
            ],
        ),
    ]
