# Generated by Django 4.0 on 2023-01-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='parend_id',
        ),
    ]
