# Generated by Django 4.0 on 2023-01-14 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_good_count_alter_tweet_user_id_and_more'),
        ('good', '0003_goodcomment_goodtweet_delete_goodparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodcomment',
            name='good_id',
        ),
        migrations.RemoveField(
            model_name='goodtweet',
            name='good_id',
        ),
        migrations.AddField(
            model_name='goodcomment',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodcomment_users', to='tweet.user'),
        ),
        migrations.AddField(
            model_name='goodtweet',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodtweet_users', to='tweet.user'),
        ),
        migrations.AlterField(
            model_name='goodcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goodtweet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
